// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: database.sql

package sqlc

import (
	"context"
)

const countAppliedMigrations = `-- name: CountAppliedMigrations :one
SELECT COUNT(*)
FROM schema_migrations
`

func (q *Queries) CountAppliedMigrations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAppliedMigrations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ensureSchemaMigrationsTable = `-- name: EnsureSchemaMigrationsTable :exec
CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY,
    applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)
`

func (q *Queries) EnsureSchemaMigrationsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ensureSchemaMigrationsTable)
	return err
}

const isMigrationApplied = `-- name: IsMigrationApplied :one
SELECT EXISTS(
    SELECT 1
    FROM schema_migrations
    WHERE version = ?
)
`

func (q *Queries) IsMigrationApplied(ctx context.Context, version int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, isMigrationApplied, version)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const recordMigration = `-- name: RecordMigration :exec
INSERT INTO schema_migrations (version)
VALUES (?)
`

func (q *Queries) RecordMigration(ctx context.Context, version int64) error {
	_, err := q.db.ExecContext(ctx, recordMigration, version)
	return err
}
