// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate_limits.sql

package sqlc

import (
	"context"
	"time"
)

const getRateLimit = `-- name: GetRateLimit :one
SELECT key_hash, last_attempt
FROM rate_limits
WHERE key_hash = ?
`

func (q *Queries) GetRateLimit(ctx context.Context, keyHash string) (RateLimit, error) {
	row := q.db.QueryRowContext(ctx, getRateLimit, keyHash)
	var i RateLimit
	err := row.Scan(&i.KeyHash, &i.LastAttempt)
	return i, err
}

const pruneRateLimits = `-- name: PruneRateLimits :exec
DELETE FROM rate_limits
WHERE last_attempt <= ?
`

func (q *Queries) PruneRateLimits(ctx context.Context, lastAttempt time.Time) error {
	_, err := q.db.ExecContext(ctx, pruneRateLimits, lastAttempt)
	return err
}

const upsertRateLimit = `-- name: UpsertRateLimit :exec
INSERT INTO rate_limits (key_hash, last_attempt)
VALUES (?, ?)
ON CONFLICT(key_hash) DO UPDATE
SET last_attempt = excluded.last_attempt
`

type UpsertRateLimitParams struct {
	KeyHash     string
	LastAttempt time.Time
}

func (q *Queries) UpsertRateLimit(ctx context.Context, arg UpsertRateLimitParams) error {
	_, err := q.db.ExecContext(ctx, upsertRateLimit, arg.KeyHash, arg.LastAttempt)
	return err
}
