// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suggestions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countSubmissions = `-- name: CountSubmissions :one
SELECT COUNT(*) FROM submissions
`

func (q *Queries) CountSubmissions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubmissions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSuggestions = `-- name: CountSuggestions :one
SELECT COUNT(*) FROM suggestions
`

func (q *Queries) CountSuggestions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSuggestions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (
    token_hash,
    author_name
)
VALUES (?, ?)
RETURNING id, author_name, token_hash, created_at
`

type CreateSubmissionParams struct {
	TokenHash  sql.NullString
	AuthorName sql.NullString
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRowContext(ctx, createSubmission, arg.TokenHash, arg.AuthorName)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.AuthorName,
		&i.TokenHash,
		&i.CreatedAt,
	)
	return i, err
}

const createSuggestion = `-- name: CreateSuggestion :one
INSERT INTO suggestions (
    submission_id,
    field_name,
    name
)
VALUES (?, ?, ?)
RETURNING id, submission_id, field_name, name, created_at
`

type CreateSuggestionParams struct {
	SubmissionID int64
	FieldName    string
	Name         string
}

func (q *Queries) CreateSuggestion(ctx context.Context, arg CreateSuggestionParams) (Suggestion, error) {
	row := q.db.QueryRowContext(ctx, createSuggestion, arg.SubmissionID, arg.FieldName, arg.Name)
	var i Suggestion
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.FieldName,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getSubmissionByTokenHash = `-- name: GetSubmissionByTokenHash :one
SELECT id, author_name, token_hash, created_at
FROM submissions
WHERE token_hash = ?
`

func (q *Queries) GetSubmissionByTokenHash(ctx context.Context, tokenHash sql.NullString) (Submission, error) {
	row := q.db.QueryRowContext(ctx, getSubmissionByTokenHash, tokenHash)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.AuthorName,
		&i.TokenHash,
		&i.CreatedAt,
	)
	return i, err
}

const listSuggestionStats = `-- name: ListSuggestionStats :many
SELECT field_name, name, COUNT(*) AS suggestion_count
FROM suggestions
GROUP BY field_name, name
ORDER BY field_name, suggestion_count DESC, name
`

type ListSuggestionStatsRow struct {
	FieldName       string
	Name            string
	SuggestionCount int64
}

func (q *Queries) ListSuggestionStats(ctx context.Context) ([]ListSuggestionStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSuggestionStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSuggestionStatsRow
	for rows.Next() {
		var i ListSuggestionStatsRow
		if err := rows.Scan(&i.FieldName, &i.Name, &i.SuggestionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuggestionVoters = `-- name: ListSuggestionVoters :many
SELECT suggestions.field_name, suggestions.name, submissions.author_name
FROM suggestions
JOIN submissions ON submissions.id = suggestions.submission_id
ORDER BY suggestions.field_name, suggestions.name, submissions.created_at, submissions.id
`

type ListSuggestionVotersRow struct {
	FieldName  string
	Name       string
	AuthorName sql.NullString
}

func (q *Queries) ListSuggestionVoters(ctx context.Context) ([]ListSuggestionVotersRow, error) {
	rows, err := q.db.QueryContext(ctx, listSuggestionVoters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSuggestionVotersRow
	for rows.Next() {
		var i ListSuggestionVotersRow
		if err := rows.Scan(&i.FieldName, &i.Name, &i.AuthorName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuggestions = `-- name: ListSuggestions :many
SELECT id, submission_id, field_name, name, created_at
FROM suggestions
ORDER BY created_at DESC
`

func (q *Queries) ListSuggestions(ctx context.Context) ([]Suggestion, error) {
	rows, err := q.db.QueryContext(ctx, listSuggestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Suggestion
	for rows.Next() {
		var i Suggestion
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.FieldName,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
