// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migrations.sql

package migrationsqlc

import (
	"context"
)

const migration001CreateSubmissions = `-- name: Migration001CreateSubmissions :exec
CREATE TABLE IF NOT EXISTS submissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_name TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)
`

func (q *Queries) Migration001CreateSubmissions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, migration001CreateSubmissions)
	return err
}

const migration001CreateSuggestions = `-- name: Migration001CreateSuggestions :exec
CREATE TABLE IF NOT EXISTS suggestions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    submission_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (submission_id, name),
    FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE
)
`

func (q *Queries) Migration001CreateSuggestions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, migration001CreateSuggestions)
	return err
}

const migration002AddSuggestionField = `-- name: Migration002AddSuggestionField :exec
ALTER TABLE suggestions
    ADD COLUMN field_name TEXT NOT NULL DEFAULT 'suggestions'
`

func (q *Queries) Migration002AddSuggestionField(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, migration002AddSuggestionField)
	return err
}

const migration002CopySubmissions = `-- name: Migration002CopySubmissions :exec
INSERT INTO submissions_new (id, author_name, created_at)
SELECT id, author_name, created_at
FROM submissions
`

func (q *Queries) Migration002CopySubmissions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, migration002CopySubmissions)
	return err
}

const migration002CopySuggestions = `-- name: Migration002CopySuggestions :exec
INSERT INTO suggestions_new (id, submission_id, field_name, name, created_at)
SELECT id, submission_id, field_name, name, created_at
FROM suggestions
`

func (q *Queries) Migration002CopySuggestions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, migration002CopySuggestions)
	return err
}

const migration002CreateSubmissionsReplacement = `-- name: Migration002CreateSubmissionsReplacement :exec
CREATE TABLE submissions_new (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_name TEXT,
    token_hash TEXT UNIQUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)
`

func (q *Queries) Migration002CreateSubmissionsReplacement(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, migration002CreateSubmissionsReplacement)
	return err
}

const migration002CreateSuggestionsReplacement = `-- name: Migration002CreateSuggestionsReplacement :exec
CREATE TABLE suggestions_new (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    submission_id INTEGER NOT NULL,
    field_name TEXT NOT NULL,
    name TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (submission_id, field_name, name),
    FOREIGN KEY (submission_id) REFERENCES submissions_new(id) ON DELETE CASCADE
)
`

func (q *Queries) Migration002CreateSuggestionsReplacement(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, migration002CreateSuggestionsReplacement)
	return err
}

const migration002DropOldSubmissions = `-- name: Migration002DropOldSubmissions :exec
DROP TABLE submissions
`

func (q *Queries) Migration002DropOldSubmissions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, migration002DropOldSubmissions)
	return err
}

const migration002DropOldSuggestions = `-- name: Migration002DropOldSuggestions :exec
DROP TABLE suggestions
`

func (q *Queries) Migration002DropOldSuggestions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, migration002DropOldSuggestions)
	return err
}

const migration002RenameSubmissions = `-- name: Migration002RenameSubmissions :exec
ALTER TABLE submissions_new RENAME TO submissions
`

func (q *Queries) Migration002RenameSubmissions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, migration002RenameSubmissions)
	return err
}

const migration002RenameSuggestions = `-- name: Migration002RenameSuggestions :exec
ALTER TABLE suggestions_new RENAME TO suggestions
`

func (q *Queries) Migration002RenameSuggestions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, migration002RenameSuggestions)
	return err
}

const migration003CreateRateLimits = `-- name: Migration003CreateRateLimits :exec
CREATE TABLE rate_limits (
    key_hash TEXT PRIMARY KEY,
    last_attempt DATETIME NOT NULL
)
`

func (q *Queries) Migration003CreateRateLimits(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, migration003CreateRateLimits)
	return err
}
