// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package migrationsqlc

import (
	"database/sql"
	"time"
)

type RateLimit struct {
	KeyHash     string
	LastAttempt time.Time
}

type SchemaMigration struct {
	Version   int64
	AppliedAt time.Time
}

type Submission struct {
	ID         int64
	AuthorName sql.NullString
	TokenHash  sql.NullString
	CreatedAt  time.Time
}

type SubmissionsNew struct {
	ID         int64
	AuthorName sql.NullString
	TokenHash  sql.NullString
	CreatedAt  time.Time
}

type Suggestion struct {
	ID           int64
	SubmissionID int64
	FieldName    string
	Name         string
	CreatedAt    time.Time
}

type SuggestionsNew struct {
	ID           int64
	SubmissionID int64
	FieldName    string
	Name         string
	CreatedAt    time.Time
}
